/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DiyEmoji: typeof import('./src/components/DiyEmoji/DiyEmoji.vue')['default']
    DiyWindowTools: typeof import('./src/components/DiyWindowTools.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    EmojiBody: typeof import('./src/components/DiyEmoji/EmojiBody.vue')['default']
    EmojiFoot: typeof import('./src/components/DiyEmoji/EmojiFoot.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
